### ISSUE TITLE
Support for Apple M1

### ISSUE THREAD

**Issue by flemzord** [wemake-services/caddy-gen#61]
Hello, 

Wen i run your container in my Apple M1, I have this error : 

proxy_1              | 2021/07/27 14:37:44 Contents of /etc/caddy/Caddyfile did not change. Skipping notification ''
proxy_1              | runtime: failed to create new OS thread (have 2 already; errno=22)
proxy_1              | fatal error: newosproc
proxy_1              | 
proxy_1              | runtime stack:
proxy_1              | runtime.throw(0x884500, 0x9)
proxy_1              |  /usr/local/go1.6/src/runtime/panic.go:530 +0x90
proxy_1              | runtime.newosproc(0xc820026000, 0xc820035fc0)
proxy_1              |  /usr/local/go1.6/src/runtime/os1_linux.go:149 +0x18c
proxy_1              | runtime.newm(0x932358, 0x0)
proxy_1              |  /usr/local/go1.6/src/runtime/proc.go:1513 +0x135
proxy_1              | runtime.main.func1()
proxy_1              |  /usr/local/go1.6/src/runtime/proc.go:125 +0x2c
proxy_1              | runtime.systemstack(0xa8e800)
proxy_1              |  /usr/local/go1.6/src/runtime/asm_amd64.s:291 +0x79
proxy_1              | runtime.mstart()
proxy_1              |  /usr/local/go1.6/src/runtime/proc.go:1048
proxy_1              | 
proxy_1              | goroutine 1 [running]:
proxy_1              | runtime.systemstack_switch()
proxy_1              |  /usr/local/go1.6/src/runtime/asm_amd64.s:245 fp=0xc820020770 sp=0xc820020768
proxy_1              | runtime.main()
proxy_1              |  /usr/local/go1.6/src/runtime/proc.go:126 +0x62 fp=0xc8200207c0 sp=0xc820020770
proxy_1              | runtime.goexit()
proxy_1              |  /usr/local/go1.6/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8200207c8 sp=0xc8200207c0

Regards, 
Maxence

**Comment by ro31337** [comment]
Thanks for the bug report, do you have minimal steps to reproduce? @flemzord

**Comment by flemzord** [comment]
I will make a PR to propose a fix :)

**Comment by flemzord** [comment]
PR #62
